### ISSUE TITLE
Question about mapping

### ISSUE THREAD

**Issue by mrvollger** [lh3/unimap#2]
Hi,

This looks like a very useful tool! Does it extend the ~1-1 chaining algorithm down to base pair level alignment? i.e. does this improve 1-1 mappings in very complex regions?

Thanks in advance!
Mitchell

**Comment by lh3** [comment]
Haven't checked. Unimap is just minigraph chaining combined with minimap2 alignment. You wouldn't see much improvement over these two.

**Comment by mrvollger** [comment]
Thanks for the quick response! I will let you know if I see improvements in SD regions.

**Comment by lh3** [comment]
A bit more details. Minimap2 uses dynamic programming (DP) for chaining. It applies a heuristic to speed up chaining as full DP is too slow, especially with large bandwidth. The heuristic, however, leads to suboptimal alignment around large segdups. I have seen multiple examples. This motivated the development of minigraph chaining.

The base alignment module in unimap is nearly identical to minimap2. The difference between unimap and minimap2 mostly comes from chaining.
