### ISSUE TITLE
LICENSE.txt not in the source tree

### ISSUE THREAD

**Issue by mbargull** [lh3/unimap#5]
Hi @lh3,

given that this is a minimap2 (+minigraph) fork, I'd assume you intended this to be MIT-licensed as well, but I couldn't find a license here.
I'm currently in the process of packaging dipcall/unimap/bedtk for Bioconda and in need of a license information file so we are able to distribute unimap :).

Cheers,
Marcel

**Comment by lh3** [comment]
Thanks. Added.

**Comment by mbargull** [comment]
Thanks, much appreciated!
